config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'books' => 'books#create'
  get 'books' => 'books#index'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title,:body,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book=Book.new
  end
  def show
    @book = Book.find params[:id]
  end
  def create
    @books = Book.all
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to @book
    else 
      render'index'
    end
  end
  def update
    @book = Book.find params[:id]
    if @book.update(book_params)
      flash[:update] = "Book was successfully updated."
      redirect_to @book
    else
      render 'edit'
    end
  end
  def edit
    @book = Book.find params[:id]
  end
  def destroy
    @book = Book.find params[:id]
    @book.destroy
    redirect_to books_path
  end
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/edit.html.erb
<h3>New book</h3>
<!-- form_for部分 -->
<%= form_for :book, url: book_path, method: :patch do |f| %>
    <% if @book.errors.any? %>
        <% @book.errors.full_messages.each do |msg| %>
        <%= msg %><br>
        <% end %>
    <% end %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<br><%= f.submit 'Update Book' %></br>

<% end %>
<%= link_to "show", book_path(@book)%>
<%= link_to "Back" ,books_path%>

app/views/books/index.html.erb
<h1>Books</h1>
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Body</th>
            <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
        <% @books.each do |book| %>
        <tr>
            <td><%= book.title %></td>
            <td><%= book.body %></td>
            <td><%= link_to "show", book_path(book)%></td>
            <td><%= link_to "edit", edit_book_path(book)%></td>
            <td><%= link_to "destroy", book_path(book), method: :delete, data: {confirm:"本当によろしいですか?"} %></td>
        </tr>
        <% end %>
    </tbody>

</table>
<h3>New book</h3>
<!-- form_for部分 -->
<%= form_for :book, url: books_path do |f| %>
    <% if @book.errors.any? %>
        <% @book.errors.full_messages.each do |msg| %>
        <%= msg %><br>
        <% end %>
    <% end %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<br><%= f.submit 'Create Book' %></br>

<% end %>

app/views/books/new.html.erb
<h3>New book</h3>
<!-- form_for部分 -->
<%= form_for :book, url: books_path do |f| %>
    <% if @book.errors.any? %>
        <% @book.errors.full_messages.each do |msg| %>
        <%= msg %><br>
        <% end %>
    <% end %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<br><%= f.submit 'Create Book' %></br>

<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
<div class="flash">
  <%= flash[:notice] %>
</div>
<% end %>
<% if flash[:update] %>
<div class="flash">
  <%= flash[:update] %>
</div>
<% end %>
<h2>Title</h2>
<p><%= @book.title %></p>
<h2>Body</h2>
<p><%= @book.body %></p>
<%= link_to "edit", edit_book_path(@book)%>
<%= link_to "Back" ,books_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>ようこそBookersへ!</h1>
<p><strong>Bookers</strong>では、様々な書籍に関するあなたの意見や</p>
<p>印象を共有できます</p>
<p><%= link_to "start", books_path %></p>